Apple iOS and iPadOS
Apple
Android
Firefox
QNAP
Drupal
SonicWall 
Intel 
Fortinet 
Cisco 
Adobe Reader/Acrobat
Google Chrome
Bluetooth devices
VMware
Cisco IOS XR Software
XZ Utils
Ivanti Products
Palo Alto
Oracle Java and Oracle Products
Git
Citrix Products
Juniper Networks
Juniper Networks Products
Sophos Firewall
Veeam
Erlang/OTP
Ivanti 
Microsoft SharePoint Server
FortiSIEM Products
F5 Products
Cisco Products
Oracle E-Business Suite